//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH4_BT2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_NHANVIENEntities : DbContext
    {
        public QL_NHANVIENEntities()
            : base("name=QL_NHANVIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chucvu> chucvus { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<phongban> phongbans { get; set; }
        public virtual DbSet<quatrinhluong> quatrinhluongs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
