//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH4_BT3
{
    using System;
    using System.Collections.Generic;
    
    public partial class quatrinhluong
    {
        public string manv { get; set; }
        public System.DateTime ngaybd { get; set; }
        public Nullable<decimal> hsluong { get; set; }
        public string ghichu { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
